listeners=http://0.0.0.0:8083
group.id=connect-cluster
rest.port=8083
plugin.path=/usr/share/java/connect_plugins
offset.flush.interval.ms=10000

config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
status.storage.topic=connect-status

config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

rest.extension.classes=com.github.mredjem.kafka.connect.extensions.SecretRegistryExtension

config.providers=secretregistry
config.providers.secretregistry.class=com.github.mredjem.kafka.connect.providers.InternalSecretConfigProvider
config.providers.secretregistry.param.kafkastore.bootstrap.servers=localhost:9092
# Config Provider must be allowed to list topics and create 'config.providers.secretregistry.param.kafkastore.topic' topic if not already present
config.providers.secretregistry.param.kafkastore.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>" password="<password>";
config.providers.secretregistry.param.kafkastore.sasl.mechanism=PLAIN
config.providers.secretregistry.param.kafkastore.security.protocol=SASL_SSL
# Internal Topic that will store secrets, will be created at startup if not already present
# Should be configured as follows if manually created:
# - num.partitions=1
# - cleanup.policy=compact
config.providers.secretregistry.param.kafkastore.topic=_connect-secrets
config.providers.secretregistry.param.kafkastore.topic.replication.factor=1
# Master Key used to encrypt secrets (should not be reused)
config.providers.secretregistry.param.master.encryption.key=juby895fmddr5hw58839d3myz27zw206ffxiv68m
# Config Provider must be granted DeveloperRead role on consumer groups prefixed with 'config.providers.secretregistry.param.secret.registry.group.id'
config.providers.secretregistry.param.secret.registry.group.id=secret-registry
