listeners=http://0.0.0.0:8083
group.id=connect-cluster
rest.port=8083
plugin.path=/usr/share/java/connect_plugins
offset.flush.interval.ms=10000

config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
status.storage.topic=connect-status

config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

# RbacAuthorizerExtension will enable role based authentication/authorization and requires 'confluent.cloud' configuration block to be present
rest.extension.classes=com.github.mredjem.kafka.connect.extensions.RbacAuthorizerExtension,com.github.mredjem.kafka.connect.extensions.SecretRegistryExtension

# Cloud Cluster Resource CRN -> see https://docs.confluent.io/cloud/current/security/access-control/hierarchy/confluent-resource-names.html
confluent.cloud.cluster.crn.pattern=crn://confluent.cloud/organization=9bb441c4-edef-46ac-8a41-c49e44a3fd9a/environment=env-456xy/cloud-cluster=lkc-123abc
# Confluent Cloud API Key allowed to list identity providers / identity pools
# Service Account should have either role among:
# - CloudClusterAdmin (recommanded)
# - AccountAdmin
# - EnvironmentAdmin
# - OrganizationAdmin
confluent.cloud.api.key=ABCDEFGHIJKLMNOP
confluent.cloud.api.secret=R15hoiDIq8Nxu/lY4mPO3DwAVIfU5W7OI+efsB607mLgHTnVW5XJGVqX2ysDx987
# Name of your OIDC Workload Identity in Confluent Cloud
confluent.cloud.identity.provider.name=azure

config.providers=secret
config.providers.secret.class=com.github.mredjem.kafka.connect.providers.InternalSecretConfigProvider
config.providers.secret.param.kafkastore.bootstrap.servers=localhost:9092
# Config Provider must be allowed to list topics and create 'config.providers.secret.param.kafkastore.topic' topic if not already present
config.providers.secret.param.kafkastore.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>" password="<password>";
config.providers.secret.param.kafkastore.sasl.mechanism=PLAIN
config.providers.secret.param.kafkastore.security.protocol=SASL_SSL
# Internal Topic that will store secrets, will be created at startup if not already present
# Should be configured as follows if manually created:
# - num.partitions=1
# - cleanup.policy=compact
config.providers.secret.param.kafkastore.topic=_connect-secrets
config.providers.secret.param.kafkastore.topic.replication.factor=1
# Master Key used to encrypt secrets (should not be reused)
config.providers.secret.param.master.encryption.key=juby895fmddr5hw58839d3myz27zw206ffxiv68m
# Config Provider must be granted DeveloperRead role on consumer groups prefixed with 'config.providers.secret.param.secret.registry.group.id'
config.providers.secret.param.secret.registry.group.id=secret-registry
