listeners=http://0.0.0.0:8083
group.id=connect-cluster
rest.port=8083
plugin.path=/usr/share/java/connect_plugins
offset.flush.interval.ms=10000

config.storage.topic=connect-configs
offset.storage.topic=connect-offsets
status.storage.topic=connect-status

config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.storage.StringConverter

rest.extension.classes=com.github.mredjem.kafka.connect.extensions.SecretRegistryExtension

config.providers=secret
config.providers.secret.class=com.github.mredjem.kafka.connect.providers.InternalSecretConfigProvider
config.providers.secret.param.kafkastore.bootstrap.servers=localhost:9092
config.providers.secret.param.kafkastore.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>" password="<password>";
config.providers.secret.param.kafkastore.sasl.mechanism=PLAIN
config.providers.secret.param.kafkastore.security.protocol=SASL_SSL
config.providers.secret.param.kafkastore.topic=_confluent-secrets
config.providers.secret.param.kafkastore.topic.replication.factor=1
config.providers.secret.param.master.encryption.key=juby895fmddr5hw58839d3myz27zw206ffxiv68m
config.providers.secret.param.secret.registry.group.id=secret-registry
