name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 8
          maven-version: 3.9.0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx --package @semantic-release/changelog --package @semantic-release/exec --package @semantic-release/git semantic-release
  
  sonar:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    needs: release
    if: always() && needs.release.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.19.0
        with:
          java-version: 11
          maven-version: 3.9.0

      - name: Run Sonar Analysis
        working-directory: ./connect-extension
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.5.0.6356:sonar
